//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoivasovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtumat
    {
        public int TapahtumaID { get; set; }
        public string Otsikko { get; set; }
        public string Teksti { get; set; }
        public string Kirjaaja { get; set; }
        public Nullable<System.DateTime> TapahtumaAika { get; set; }
        public int AsiakasID { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
    }
}
